# Generated by Django 5.2.5 on 2025-08-18 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tfidf_similarity', max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('training_status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='training', max_length=20)),
                ('training_dataset_size', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('training_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('training_started_at', models.DateTimeField(auto_now_add=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('training_started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-training_started_at'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
